name : first.yaml
on : [push]
jobs:
  run-shell-commands:
    run-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: run multiple commands
        run: |
         node -v
         npm  -v
         
